import express from 'express';
import { authMiddleware } from '@/middleware';
import * as c from '@/controllers/v1/conversations';
const router = express.Router();
router.use(authMiddleware({ checkPermission: true }));
router.post('/', c.messagingCreateController);
router.post('/devices', c.messagingEnrollController);
router.get('/users/:id/devices', c.messagingRosterController);
router.post('/devices/:deviceId/claim', c.messagingClaimController);
router.post('/devices/:deviceId/revoke', c.messagingRevokeController);
router.get('/users/:id/conversations', c.messagingListController);
router.get('/users/:id/recipients/:recipientId/messages', c.messagingPeerController);
router.get('/:id/messages', c.messagingSyncController);
router.post('/messages', c.messagingSendController);
router.post('/receipts/batch',c.messagingReceiptBatchController);
router.post('/receipts', c.messagingReceiptController);
router.post('/:id/request', c.messagingRequestController);
router.delete('/:id/messages/:messageId', c.messagingDeleteController);
router.post('/:id/blobs',c.messagingReserveController);
router.post('/:id/blobs/:blobId/finalize',c.messagingFinalizeController);
router.get('/:id/blobs/:blobId', c.messagingDownloadController);
export default router;
