import { beforeAll, afterAll, beforeEach, expect, it } from 'vitest';
import { randomUUID } from 'node:crypto';
import db from '@/db';
import * as chat from '@/services/v1/conversations';
const users = ['e2-a', 'e2-b', 'e2-outsider'];
let a: string, b: string, c: string;
const session = 'e2-session';
const bundle = (deviceId: string, number: number) => ({ deviceId, signalDeviceId: number, registrationId: 42, identityPublic: Buffer.alloc(33, number).toString('base64'), actionSigningPublic: Buffer.alloc(32, number).toString('base64'), signedPreKey: { keyId: 1, publicKey: Buffer.alloc(33, 3).toString('base64'), signature: Buffer.alloc(64, 4).toString('base64') }, preKeys: [{ keyId: 1, publicKey: Buffer.alloc(33, 5).toString('base64') }] });
const send = (conversationId: string, clientId = randomUUID()) => ({ conversationId, clientId, envelopes: [{ recipientDeviceId: b, wireType: 3 as const, ciphertextB64: Buffer.alloc(64, 7).toString('base64') }] });
beforeAll(async () => { await db.user.createMany({ data: users.map(id => ({ id, name: id, username: id, email: `${id}@test.invalid`, emailVerifiedAt: new Date() })), skipDuplicates: true }); });
beforeEach(async () => { await db.e2Outbox.deleteMany({}); await db.e2Conversation.deleteMany({}); await db.e2PreKeyClaim.deleteMany({}); await db.e2Device.deleteMany({}); await db.blockUser.deleteMany({ where: { blockerId: { in: users } } }); await db.follow.deleteMany({ where: { followerId: { in: users } } }); a = randomUUID(); b = randomUUID(); c = randomUUID(); await chat.enrollMessagingDevice(users[0], session, bundle(a, 1)); await chat.enrollMessagingDevice(users[1], session, bundle(b, 2)); await chat.enrollMessagingDevice(users[2], session, bundle(c, 3)); });
afterAll(async () => { await db.e2Outbox.deleteMany({}); await db.e2Conversation.deleteMany({}); await db.e2PreKeyClaim.deleteMany({}); await db.e2Device.deleteMany({}); await db.$disconnect(); });
it('creates exactly one canonical pair under concurrent reversed initiations and only mutual accepted follows bypass requests', async () => {
    const rows = await Promise.all([chat.createMessagingConversation(users[0], users[1]), chat.createMessagingConversation(users[1], users[0])]);
    expect(rows[0].id).toBe(rows[1].id);
    expect(rows[0].state).toBe('PENDING_REQUEST');
    expect(await db.e2Conversation.count()).toBe(1);
    await db.e2Conversation.deleteMany({});
    await db.follow.createMany({ data: [{ followerId: users[0], followingId: users[1], status: 'ACCEPTED' }, { followerId: users[1], followingId: users[0], status: 'ACCEPTED' }] });
    expect((await chat.createMessagingConversation(users[0], users[1])).state).toBe('ACCEPTED');
});
it('prekey claims are single-use under contention, idempotent and public-only', async () => {
    const claims = await Promise.all(Array.from({ length: 8 }, () => chat.claimMessagingPreKey(users[0], session, a, b, randomUUID()))) as any[];
    expect(claims.filter(v => v.preKey)).toHaveLength(1);
    expect(JSON.stringify(claims)).not.toMatch(/privKey|privateKey/);
    const id = randomUUID();
    const first = await chat.claimMessagingPreKey(users[0], session, a, b, id);
    expect(await chat.claimMessagingPreKey(users[0], session, a, b, id)).toEqual(first);
    await expect(chat.claimMessagingPreKey(users[0], session, a, c, id)).rejects.toThrow('Claim conflict');
});
it('silent pending preview suppresses delivered/read/typing; acceptance activates only exact processed IDs', async () => {
    const convo = await chat.createMessagingConversation(users[0], users[1]);
    const one = await chat.sendMessagingEvent(users[0], session, a, send(convo.id));
    const two = await chat.sendMessagingEvent(users[0], session, a, send(convo.id));
    const preview = await chat.messagingSync(users[1], session, b, convo.id, '0');
    expect(preview.messages).toHaveLength(2);
    expect(await chat.messagingReceipt(users[1], session, b, { conversationId: convo.id, messageIds: [one.messageId], status: 'READ' })).toEqual({ suppressed: true });
    expect(await db.e2Receipt.count()).toBe(0);
    expect(await chat.messagingTyping(users[1], session, b, convo.id)).toBeNull();
    await expect(chat.resolveMessagingRequest(users[0], session, a, convo.id, { action: 'accept', deliveredIds: [], readIds: [] })).rejects.toThrow('Request unavailable');
    await chat.resolveMessagingRequest(users[1], session, b, convo.id, { action: 'accept', deliveredIds: [one.messageId], readIds: [one.messageId] });
    expect(await db.e2Receipt.findMany()).toMatchObject([{ messageId: one.messageId, status: 'READ' }]);
    expect(await db.e2Receipt.count({ where: { messageId: two.messageId } })).toBe(0);
    const sender = await chat.messagingSync(users[0], session, a, convo.id, '0');
    expect(sender.receipts).toHaveLength(1);
    expect(sender.receipts.at(-1)).toMatchObject({ status: 'READ', id: one.messageId });
    expect(await chat.messagingTyping(users[1], session, b, convo.id)).toBe(users[0]);
    await chat.messagingReceipt(users[1], session, b, { conversationId: convo.id, messageIds: [one.messageId], status: 'DELIVERED' });
    expect((await db.e2Receipt.findFirst())?.status).toBe('READ');
});
it('rejects outsiders, forged receipts, device impersonation and revoked sessions', async () => {
    const convo = await chat.createMessagingConversation(users[0], users[1]);
    await expect(chat.messagingSync(users[2], session, c, convo.id, '0')).rejects.toThrow('Conversation not found');
    await expect(chat.sendMessagingEvent(users[0], session, b, send(convo.id))).rejects.toThrow('Unlock');
    await expect(chat.sendMessagingEvent(users[0], 'other-session', a, send(convo.id))).rejects.toThrow('Unlock');
    const one = await chat.sendMessagingEvent(users[0], session, a, send(convo.id));
    await chat.resolveMessagingRequest(users[1], session, b, convo.id, { action: 'accept', deliveredIds: [], readIds: [] });
    await expect(chat.messagingReceipt(users[0], session, a, { conversationId: convo.id, messageIds: [one.messageId], status: 'READ' })).rejects.toThrow('Receipts');
    await expect(chat.messagingReceipt(users[1], session, b, { conversationId: convo.id, messageIds: [randomUUID()], status: 'READ' })).rejects.toThrow('Receipts');
    await chat.revokeMessagingDevice(users[0], a);
    await expect(chat.messagingDevice(users[0], session, a)).rejects.toThrow('Unlock');
    expect(await chat.messagingRoster(users[1], users[0])).toEqual([]);
});
it('keeps exact ciphertext retries idempotent and rejects changed bytes or invalid recipient rosters', async () => {
    const convo = await chat.createMessagingConversation(users[0], users[1]);
    const input = send(convo.id);
    const one = await chat.sendMessagingEvent(users[0], session, a, input);
    expect(await chat.sendMessagingEvent(users[0], session, a, input)).toEqual(one);
    expect(await db.e2Message.count()).toBe(1);
    await expect(chat.sendMessagingEvent(users[0], session, a, { ...input, envelopes: [{ ...input.envelopes[0], ciphertextB64: Buffer.alloc(64, 8).toString('base64') }] })).rejects.toThrow('different ciphertext');
    await expect(chat.sendMessagingEvent(users[0], session, a, { ...send(convo.id), envelopes: [{ ...input.envelopes[0], recipientDeviceId: c }] })).rejects.toThrow('roster');
});
it('rejection purges recipient envelopes, keeps sender status private, discards later sends and persists block policy', async () => {
    const convo = await chat.createMessagingConversation(users[0], users[1]);
    await chat.sendMessagingEvent(users[0], session, a, send(convo.id));
    await chat.resolveMessagingRequest(users[1], session, b, convo.id, { action: 'block', deliveredIds: [], readIds: [] });
    expect(await db.e2Envelope.count()).toBe(0);
    expect(await chat.listMessagingConversations(users[1], 'requests', 1, 21)).toEqual([]);
    expect((await chat.messagingSync(users[0], session, a, convo.id, '0')).conversation.state).toBe('PENDING_REQUEST');
    expect((await chat.sendMessagingEvent(users[0], session, a, send(convo.id))).status).toBe('SENT');
    expect(await db.e2Message.count()).toBe(1);
    expect(await chat.messagingRoster(users[0], users[1])).toEqual([]);
    expect(await db.blockUser.count({ where: { blockerId: users[1], blockedId: users[0] } })).toBe(1);
});
it('relays only ciphertext attachments to authorized members, excludes blocked users and supports delete-for-me', async () => {
    const convo = await chat.createMessagingConversation(users[0], users[1]);
    const id = randomUUID(), ciphertext = Buffer.alloc(64, 1);
    await db.e2Blob.create({data:{id,conversationId:convo.id,ownerDeviceId:a,objectKey:randomUUID(),ciphertext,ciphertextBytes:ciphertext.length,finalizedAt:new Date(),expiresAt:new Date(Date.now()+60000)}});
    expect(await chat.getMessagingBlob(users[1], session, b, convo.id, id)).toEqual({legacyBytes:ciphertext});
    await expect(chat.getMessagingBlob(users[2], session, c, convo.id, id)).rejects.toThrow('Conversation');
    const sent = await chat.sendMessagingEvent(users[0], session, a, send(convo.id));
    await chat.deleteMessagingForMe(users[1], session, b, convo.id, sent.messageId);
    expect((await chat.messagingSync(users[1], session, b, convo.id, '0')).messages).toEqual([]);
    expect((await chat.messagingSync(users[0], session, a, convo.id, '0')).messages).toHaveLength(1);
    await db.blockUser.create({ data: { blockerId: users[1], blockedId: users[0] } });
    await expect(chat.getMessagingBlob(users[1], session, b, convo.id, id)).rejects.toThrow('unavailable');
});
it('does not replace device identities or reset consumed prekeys during reenrollment', async () => {
    const input = bundle(a, 1);
    await chat.enrollMessagingDevice(users[0], session, input);
    await chat.claimMessagingPreKey(users[1], session, b, a, randomUUID());
    await chat.enrollMessagingDevice(users[0], session, input);
    expect(await db.e2OneTimePreKey.count({ where: { deviceId: a, claimedAt: null } })).toBe(0);
    await expect(chat.enrollMessagingDevice(users[1], session, input)).rejects.toThrow('identity');
    await expect(chat.enrollMessagingDevice(users[0], session, { ...input, identityPublic: Buffer.alloc(33, 9).toString('base64') })).rejects.toThrow('identity');
});

it('enrolls fifty prekeys atomically and retries without republishing consumed keys',async()=>{
 const id=randomUUID();const input={...bundle(id,4),preKeys:Array.from({length:50},(_,i)=>({keyId:i+1,publicKey:Buffer.alloc(33,i+1).toString('base64')}))};
 await chat.enrollMessagingDevice(users[0],session,input);
 expect(await db.e2OneTimePreKey.count({where:{deviceId:id}})).toBe(50);
 const claimed=await chat.claimMessagingPreKey(users[1],session,b,id,randomUUID()) as any;
 await chat.enrollMessagingDevice(users[0],session,input);
 expect(await db.e2OneTimePreKey.count({where:{deviceId:id}})).toBe(50);
 expect(await db.e2OneTimePreKey.count({where:{deviceId:id,claimedAt:null}})).toBe(49);
 const conflicting={...input,preKeys:input.preKeys.map(k=>k.keyId===claimed.preKey.keyId?{...k,publicKey:Buffer.alloc(33,99).toString('base64')}:k)};
 await expect(chat.enrollMessagingDevice(users[0],'changed-session',conflicting)).rejects.toThrow('Prekey ID cannot be reused');
 expect((await db.e2Device.findUniqueOrThrow({where:{id}})).sessionId).toBe(session);
});
