import {PrismaPg} from "@prisma/adapter-pg";
import {afterAll, beforeAll, expect, it, vi} from 'vitest';
import {createHash} from 'node:crypto';
import {PrismaClient} from '@prisma/client';
const classify = vi.hoisted(() => vi.fn());
vi.mock('@/utils/helpers', () => ({topicClassifier: classify, AppError: class extends Error {}}));
import {inferPostTopic} from '@/services/v1/posts';
import {run} from '@/cron/recurring/infer_pending_post_topics';
import {postTopicQueue} from '@/cron/jobs/queue';
import {POST_TOPIC_MODEL_VERSION} from '@/cron/helpers';
const db = new PrismaClient({adapter: new PrismaPg({connectionString: process.env.DATABASE_URL, max: 10, connectionTimeoutMillis: 5000})}); let owner: string;
const content = 'AI art is changing creativity. Machines can inspire ideas, but your human touch gives it meaning and emotion.';
beforeAll(async () => {owner = (await db.user.create({data: {emailVerifiedAt: new Date(), name: 'Topic fixture', username: 'topic-model-fixture', email: 'topic-model-fixture@test.invalid'}})).id;});
afterAll(async () => {await db.post.deleteMany({where: {userId: owner}}); await db.user.delete({where: {id: owner}}); await postTopicQueue.obliterate({force: true}); await postTopicQueue.close(); await db.$disconnect();});
it('recovers unclassified posts and saves their inferred topic', async () => {
 const post = await db.post.create({data: {userId: owner, type: 'CONTENT', kind: 'ROOT', content, topic: null}});
 await run();
 expect(await db.post.findUnique({where: {id: post.id}})).toMatchObject({topic: null});
 const versionHash = createHash('sha256').update(POST_TOPIC_MODEL_VERSION).update('\0').update(content).digest('hex');
 const job = await postTopicQueue.getJob(`topic-${post.id}-${versionHash}`);
 expect(job?.data).toEqual({id: post.id, contentHash: createHash('sha256').update(content).digest('hex')});
 classify.mockResolvedValue({labels: ['technology','learning'], scores: [0.998,0.982]});
 await inferPostTopic(post.id, job!.data.contentHash);
 expect(await db.post.findUnique({where: {id: post.id}})).toMatchObject({topic: 'technology'});
});
it('preserves an existing label if the new model fails and does not overwrite an edited post', async () => {
 const post = await db.post.create({data: {userId: owner, type: 'CONTENT', kind: 'ROOT', content, topic: 'learning'}});
 classify.mockRejectedValueOnce(new Error('Model unavailable'));
 await expect(inferPostTopic(post.id)).rejects.toThrow('Model unavailable');
 expect(await db.post.findUnique({where: {id: post.id}})).toMatchObject({topic: 'learning'});
 classify.mockImplementationOnce(async () => {await db.post.update({where: {id: post.id}, data: {content: 'Edited tutorial text'}}); return {labels: ['technology'], scores: [0.99]};});
 await inferPostTopic(post.id);
 expect(await db.post.findUnique({where: {id: post.id}})).toMatchObject({content: 'Edited tutorial text', topic: null});
});
